// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <gst/gst.h>
#include <gst/gst.h>
#include <gst/app/app.h>
#include <gst/audio/audio.h>
#include <gst/base/base.h>
#include <gst/controller/controller.h>
#include <gst/fft/fft.h>
//#include <gst/mpegts/mpegts.h>
#include <gst/net/net.h>
#include <gst/pbutils/pbutils.h>
#include <gst/rtp/rtp.h>
#include <gst/rtsp/rtsp.h>
#include <gst/sdp/sdp.h>
#include <gst/tag/tag.h>
#include <gst/video/video.h>

#ifndef MYAPI
#define MYAPI __declspec(dllexport)
#endif

MYAPI guint gstsharp_gst_allocator_get_mem_type_offset (void);

MYAPI guint
gstsharp_gst_allocator_get_mem_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAllocator, mem_type);
}

MYAPI guint gstsharp_gst_allocator_get_mem_map_offset (void);

MYAPI guint
gstsharp_gst_allocator_get_mem_map_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAllocator, mem_map);
}

MYAPI guint gstsharp_gst_allocator_get_mem_unmap_offset (void);

MYAPI guint
gstsharp_gst_allocator_get_mem_unmap_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAllocator, mem_unmap);
}

MYAPI guint gstsharp_gst_allocator_get_mem_copy_offset (void);

MYAPI guint
gstsharp_gst_allocator_get_mem_copy_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAllocator, mem_copy);
}

MYAPI guint gstsharp_gst_allocator_get_mem_share_offset (void);

MYAPI guint
gstsharp_gst_allocator_get_mem_share_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAllocator, mem_share);
}

MYAPI guint gstsharp_gst_allocator_get_mem_is_span_offset (void);

MYAPI guint
gstsharp_gst_allocator_get_mem_is_span_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAllocator, mem_is_span);
}

MYAPI guint gstsharp_gst_bin_get_numchildren_offset (void);

MYAPI guint
gstsharp_gst_bin_get_numchildren_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, numchildren);
}

MYAPI guint gstsharp_gst_bin_get_children_offset (void);

MYAPI guint
gstsharp_gst_bin_get_children_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, children);
}

MYAPI guint gstsharp_gst_bin_get_children_cookie_offset (void);

MYAPI guint
gstsharp_gst_bin_get_children_cookie_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, children_cookie);
}

MYAPI guint gstsharp_gst_bin_get_child_bus_offset (void);

MYAPI guint
gstsharp_gst_bin_get_child_bus_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, child_bus);
}

MYAPI guint gstsharp_gst_bin_get_messages_offset (void);

MYAPI guint
gstsharp_gst_bin_get_messages_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, messages);
}

MYAPI guint gstsharp_gst_bin_get_polling_offset (void);

MYAPI guint
gstsharp_gst_bin_get_polling_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, polling);
}

MYAPI guint gstsharp_gst_bin_get_state_dirty_offset (void);

MYAPI guint
gstsharp_gst_bin_get_state_dirty_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, state_dirty);
}

MYAPI guint gstsharp_gst_bin_get_clock_dirty_offset (void);

MYAPI guint
gstsharp_gst_bin_get_clock_dirty_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, clock_dirty);
}

MYAPI guint gstsharp_gst_bin_get_provided_clock_offset (void);

MYAPI guint
gstsharp_gst_bin_get_provided_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, provided_clock);
}

MYAPI guint gstsharp_gst_bin_get_clock_provider_offset (void);

MYAPI guint
gstsharp_gst_bin_get_clock_provider_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBin, clock_provider);
}

MYAPI guint gstsharp_gst_bufferpool_get_flushing_offset (void);

MYAPI guint
gstsharp_gst_bufferpool_get_flushing_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBufferPool, flushing);
}

MYAPI guint gstsharp_gst_controlbinding_get_name_offset (void);

MYAPI guint
gstsharp_gst_controlbinding_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstControlBinding, name);
}

MYAPI guint gstsharp_gst_controlbinding_get_pspec_offset (void);

MYAPI guint
gstsharp_gst_controlbinding_get_pspec_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstControlBinding, pspec);
}

MYAPI guint gstsharp_gst_controlsource_get_get_value_offset (void);

MYAPI guint
gstsharp_gst_controlsource_get_get_value_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstControlSource, get_value);
}

MYAPI guint gstsharp_gst_controlsource_get_get_value_array_offset (void);

MYAPI guint
gstsharp_gst_controlsource_get_get_value_array_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstControlSource, get_value_array);
}

MYAPI guint gstsharp_gst_element_get_state_lock_offset (void);

MYAPI guint
gstsharp_gst_element_get_state_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, state_lock);
}

MYAPI guint gstsharp_gst_element_get_state_cond_offset (void);

MYAPI guint
gstsharp_gst_element_get_state_cond_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, state_cond);
}

MYAPI guint gstsharp_gst_element_get_state_cookie_offset (void);

MYAPI guint
gstsharp_gst_element_get_state_cookie_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, state_cookie);
}

MYAPI guint gstsharp_gst_element_get_target_state_offset (void);

MYAPI guint
gstsharp_gst_element_get_target_state_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, target_state);
}

MYAPI guint gstsharp_gst_element_get_current_state_offset (void);

MYAPI guint
gstsharp_gst_element_get_current_state_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, current_state);
}

MYAPI guint gstsharp_gst_element_get_next_state_offset (void);

MYAPI guint
gstsharp_gst_element_get_next_state_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, next_state);
}

MYAPI guint gstsharp_gst_element_get_pending_state_offset (void);

MYAPI guint
gstsharp_gst_element_get_pending_state_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, pending_state);
}

MYAPI guint gstsharp_gst_element_get_last_return_offset (void);

MYAPI guint
gstsharp_gst_element_get_last_return_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, last_return);
}

MYAPI guint gstsharp_gst_element_get_numpads_offset (void);

MYAPI guint
gstsharp_gst_element_get_numpads_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, numpads);
}

MYAPI guint gstsharp_gst_element_get_pads_offset (void);

MYAPI guint
gstsharp_gst_element_get_pads_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, pads);
}

MYAPI guint gstsharp_gst_element_get_numsrcpads_offset (void);

MYAPI guint
gstsharp_gst_element_get_numsrcpads_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, numsrcpads);
}

MYAPI guint gstsharp_gst_element_get_srcpads_offset (void);

MYAPI guint
gstsharp_gst_element_get_srcpads_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, srcpads);
}

MYAPI guint gstsharp_gst_element_get_numsinkpads_offset (void);

MYAPI guint
gstsharp_gst_element_get_numsinkpads_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, numsinkpads);
}

MYAPI guint gstsharp_gst_element_get_sinkpads_offset (void);

MYAPI guint
gstsharp_gst_element_get_sinkpads_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, sinkpads);
}

MYAPI guint gstsharp_gst_element_get_pads_cookie_offset (void);

MYAPI guint
gstsharp_gst_element_get_pads_cookie_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstElement, pads_cookie);
}

MYAPI guint gstsharp_gst_ghostpad_get_pad_offset (void);

MYAPI guint
gstsharp_gst_ghostpad_get_pad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstGhostPad, pad);
}

MYAPI guint gstsharp_gst_object_get_lock_offset (void);

MYAPI guint
gstsharp_gst_object_get_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstObject, lock);
}

MYAPI guint gstsharp_gst_object_get_name_offset (void);

MYAPI guint
gstsharp_gst_object_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstObject, name);
}

MYAPI guint gstsharp_gst_object_get_flags_offset (void);

MYAPI guint
gstsharp_gst_object_get_flags_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstObject, flags);
}

MYAPI guint gstsharp_gst_pad_get_padtemplate_offset (void);

MYAPI guint
gstsharp_gst_pad_get_padtemplate_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPad, padtemplate);
}

MYAPI guint gstsharp_gst_pad_get_direction_offset (void);

MYAPI guint
gstsharp_gst_pad_get_direction_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPad, direction);
}

MYAPI guint gstsharp_gst_padtemplate_get_name_template_offset (void);

MYAPI guint
gstsharp_gst_padtemplate_get_name_template_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPadTemplate, name_template);
}

MYAPI guint gstsharp_gst_padtemplate_get_direction_offset (void);

MYAPI guint
gstsharp_gst_padtemplate_get_direction_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPadTemplate, direction);
}

MYAPI guint gstsharp_gst_padtemplate_get_presence_offset (void);

MYAPI guint
gstsharp_gst_padtemplate_get_presence_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPadTemplate, presence);
}

MYAPI guint gstsharp_gst_padtemplate_get_caps_offset (void);

MYAPI guint
gstsharp_gst_padtemplate_get_caps_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPadTemplate, caps);
}

MYAPI guint gstsharp_gst_pipeline_get_fixed_clock_offset (void);

MYAPI guint
gstsharp_gst_pipeline_get_fixed_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPipeline, fixed_clock);
}

MYAPI guint gstsharp_gst_pipeline_get_stream_time_offset (void);

MYAPI guint
gstsharp_gst_pipeline_get_stream_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPipeline, stream_time);
}

MYAPI guint gstsharp_gst_pipeline_get_delay_offset (void);

MYAPI guint
gstsharp_gst_pipeline_get_delay_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstPipeline, delay);
}

MYAPI guint gstsharp_gst_proxypad_get_pad_offset (void);

MYAPI guint
gstsharp_gst_proxypad_get_pad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstProxyPad, pad);
}

MYAPI guint gstsharp_gst_systemclock_get_clock_offset (void);

MYAPI guint
gstsharp_gst_systemclock_get_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstSystemClock, clock);
}

MYAPI guint gstsharp_gst_task_get_cond_offset (void);

MYAPI guint
gstsharp_gst_task_get_cond_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTask, cond);
}

MYAPI guint gstsharp_gst_task_get_lock_offset (void);

MYAPI guint
gstsharp_gst_task_get_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTask, lock);
}

MYAPI guint gstsharp_gst_task_get_func_offset (void);

MYAPI guint
gstsharp_gst_task_get_func_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTask, func);
}

MYAPI guint gstsharp_gst_task_get_user_data_offset (void);

MYAPI guint
gstsharp_gst_task_get_user_data_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTask, user_data);
}

MYAPI guint gstsharp_gst_task_get_running_offset (void);

MYAPI guint
gstsharp_gst_task_get_running_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTask, running);
}

MYAPI guint gstsharp_gst_buffer_get_pool_offset (void);

MYAPI guint
gstsharp_gst_buffer_get_pool_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBuffer, pool);
}

MYAPI guint gstsharp_gst_buffer_get_pts_offset (void);

MYAPI guint
gstsharp_gst_buffer_get_pts_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBuffer, pts);
}

MYAPI guint gstsharp_gst_buffer_get_dts_offset (void);

MYAPI guint
gstsharp_gst_buffer_get_dts_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBuffer, dts);
}

MYAPI guint gstsharp_gst_buffer_get_duration_offset (void);

MYAPI guint
gstsharp_gst_buffer_get_duration_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBuffer, duration);
}

MYAPI guint gstsharp_gst_buffer_get_offset_offset (void);

MYAPI guint
gstsharp_gst_buffer_get_offset_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBuffer, offset);
}

MYAPI guint gstsharp_gst_buffer_get_offset_end_offset (void);

MYAPI guint
gstsharp_gst_buffer_get_offset_end_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBuffer, offset_end);
}

MYAPI guint gstsharp_gst_clockentry_get_refcount_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_refcount_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, refcount);
}

MYAPI guint gstsharp_gst_clockentry_get_clock_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, clock);
}

MYAPI guint gstsharp_gst_clockentry_get_type_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, type);
}

MYAPI guint gstsharp_gst_clockentry_get_time_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, time);
}

MYAPI guint gstsharp_gst_clockentry_get_interval_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_interval_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, interval);
}

MYAPI guint gstsharp_gst_clockentry_get_status_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_status_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, status);
}

MYAPI guint gstsharp_gst_clockentry_get_user_data_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_user_data_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, user_data);
}

MYAPI guint gstsharp_gst_clockentry_get_unscheduled_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_unscheduled_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, unscheduled);
}

MYAPI guint gstsharp_gst_clockentry_get_woken_up_offset (void);

MYAPI guint
gstsharp_gst_clockentry_get_woken_up_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstClockEntry, woken_up);
}

MYAPI guint gstsharp_gst_event_get_type_offset (void);

MYAPI guint
gstsharp_gst_event_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstEvent, type);
}

MYAPI guint gstsharp_gst_event_get_timestamp_offset (void);

MYAPI guint
gstsharp_gst_event_get_timestamp_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstEvent, timestamp);
}

MYAPI guint gstsharp_gst_iterator_get_copy_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_copy_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, copy);
}

MYAPI guint gstsharp_gst_iterator_get_next_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_next_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, next);
}

MYAPI guint gstsharp_gst_iterator_get_item_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_item_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, item);
}

MYAPI guint gstsharp_gst_iterator_get_resync_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_resync_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, resync);
}

MYAPI guint gstsharp_gst_iterator_get_free_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_free_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, free);
}

MYAPI guint gstsharp_gst_iterator_get_pushed_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_pushed_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, pushed);
}

MYAPI guint gstsharp_gst_iterator_get_type_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, type);
}

MYAPI guint gstsharp_gst_iterator_get_lock_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, lock);
}

MYAPI guint gstsharp_gst_iterator_get_cookie_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_cookie_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, cookie);
}

MYAPI guint gstsharp_gst_iterator_get_master_cookie_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_master_cookie_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, master_cookie);
}

MYAPI guint gstsharp_gst_iterator_get_size_offset (void);

MYAPI guint
gstsharp_gst_iterator_get_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstIterator, size);
}

MYAPI guint gstsharp_gst_memory_get_allocator_offset (void);

MYAPI guint
gstsharp_gst_memory_get_allocator_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMemory, allocator);
}

MYAPI guint gstsharp_gst_memory_get_parent_offset (void);

MYAPI guint
gstsharp_gst_memory_get_parent_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMemory, parent);
}

MYAPI guint gstsharp_gst_memory_get_maxsize_offset (void);

MYAPI guint
gstsharp_gst_memory_get_maxsize_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMemory, maxsize);
}

MYAPI guint gstsharp_gst_memory_get_align_offset (void);

MYAPI guint
gstsharp_gst_memory_get_align_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMemory, align);
}

MYAPI guint gstsharp_gst_memory_get_offset_offset (void);

MYAPI guint
gstsharp_gst_memory_get_offset_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMemory, offset);
}

MYAPI guint gstsharp_gst_memory_get_size_offset (void);

MYAPI guint
gstsharp_gst_memory_get_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMemory, size);
}

MYAPI guint gstsharp_gst_message_get_type_offset (void);

MYAPI guint
gstsharp_gst_message_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMessage, type);
}

MYAPI guint gstsharp_gst_message_get_timestamp_offset (void);

MYAPI guint
gstsharp_gst_message_get_timestamp_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMessage, timestamp);
}

MYAPI guint gstsharp_gst_message_get_src_offset (void);

MYAPI guint
gstsharp_gst_message_get_src_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMessage, src);
}

MYAPI guint gstsharp_gst_miniobject_get_type_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, type);
}

MYAPI guint gstsharp_gst_miniobject_get_refcount_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_refcount_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, refcount);
}

MYAPI guint gstsharp_gst_miniobject_get_lockstate_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_lockstate_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, lockstate);
}

MYAPI guint gstsharp_gst_miniobject_get_flags_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_flags_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, flags);
}

MYAPI guint gstsharp_gst_miniobject_get_copy_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_copy_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, copy);
}

MYAPI guint gstsharp_gst_miniobject_get_dispose_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_dispose_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, dispose);
}

MYAPI guint gstsharp_gst_miniobject_get_free_offset (void);

MYAPI guint
gstsharp_gst_miniobject_get_free_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMiniObject, free);
}

MYAPI guint gstsharp_gst_query_get_type_offset (void);

MYAPI guint
gstsharp_gst_query_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstQuery, type);
}

MYAPI guint gstsharp_gst_structure_get_type_offset (void);

MYAPI guint
gstsharp_gst_structure_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstStructure, type);
}

MYAPI guint gst__appsharp_gst__app_appsink_get_basesink_offset (void);

MYAPI guint
gst__appsharp_gst__app_appsink_get_basesink_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAppSink, basesink);
}

MYAPI guint gst__appsharp_gst__app_appsrc_get_basesrc_offset (void);

MYAPI guint
gst__appsharp_gst__app_appsrc_get_basesrc_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAppSrc, basesrc);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_element_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, element);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_ringbuffer_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_ringbuffer_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, ringbuffer);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_buffer_time_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_buffer_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, buffer_time);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_latency_time_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_latency_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, latency_time);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_next_sample_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_next_sample_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, next_sample);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_provided_clock_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_provided_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, provided_clock);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesink_get_eos_rendering_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesink_get_eos_rendering_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSink, eos_rendering);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesrc_get_element_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesrc_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSrc, element);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesrc_get_ringbuffer_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesrc_get_ringbuffer_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSrc, ringbuffer);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesrc_get_buffer_time_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesrc_get_buffer_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSrc, buffer_time);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesrc_get_latency_time_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesrc_get_latency_time_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSrc, latency_time);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesrc_get_next_sample_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesrc_get_next_sample_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSrc, next_sample);
}

MYAPI guint gst__audiosharp_gst__audio_audiobasesrc_get_clock_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiobasesrc_get_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioBaseSrc, clock);
}

MYAPI guint gst__audiosharp_gst__audio_audiocdsrc_get_pushsrc_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiocdsrc_get_pushsrc_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioCdSrc, pushsrc);
}

MYAPI guint gst__audiosharp_gst__audio_audiocdsrc_get_tags_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiocdsrc_get_tags_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioCdSrc, tags);
}

MYAPI guint gst__audiosharp_gst__audio_audioclock_get_clock_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioclock_get_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioClock, clock);
}

MYAPI guint gst__audiosharp_gst__audio_audioclock_get_func_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioclock_get_func_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioClock, func);
}

MYAPI guint gst__audiosharp_gst__audio_audioclock_get_user_data_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioclock_get_user_data_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioClock, user_data);
}

MYAPI guint gst__audiosharp_gst__audio_audiodecoder_get_element_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiodecoder_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioDecoder, element);
}

MYAPI guint gst__audiosharp_gst__audio_audiodecoder_get_sinkpad_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiodecoder_get_sinkpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioDecoder, sinkpad);
}

MYAPI guint gst__audiosharp_gst__audio_audiodecoder_get_srcpad_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiodecoder_get_srcpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioDecoder, srcpad);
}

MYAPI guint gst__audiosharp_gst__audio_audiodecoder_get_stream_lock_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiodecoder_get_stream_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioDecoder, stream_lock);
}

MYAPI guint gst__audiosharp_gst__audio_audiodecoder_get_input_segment_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiodecoder_get_input_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioDecoder, input_segment);
}

MYAPI guint gst__audiosharp_gst__audio_audiodecoder_get_output_segment_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiodecoder_get_output_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioDecoder, output_segment);
}

MYAPI guint gst__audiosharp_gst__audio_audioencoder_get_element_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioencoder_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioEncoder, element);
}

MYAPI guint gst__audiosharp_gst__audio_audioencoder_get_sinkpad_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioencoder_get_sinkpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioEncoder, sinkpad);
}

MYAPI guint gst__audiosharp_gst__audio_audioencoder_get_srcpad_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioencoder_get_srcpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioEncoder, srcpad);
}

MYAPI guint gst__audiosharp_gst__audio_audioencoder_get_stream_lock_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioencoder_get_stream_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioEncoder, stream_lock);
}

MYAPI guint gst__audiosharp_gst__audio_audioencoder_get_input_segment_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioencoder_get_input_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioEncoder, input_segment);
}

MYAPI guint gst__audiosharp_gst__audio_audioencoder_get_output_segment_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioencoder_get_output_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioEncoder, output_segment);
}

MYAPI guint gst__audiosharp_gst__audio_audiofilter_get_basetransform_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiofilter_get_basetransform_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioFilter, basetransform);
}

MYAPI guint gst__audiosharp_gst__audio_audiofilter_get_info_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiofilter_get_info_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioFilter, info);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_cond_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_cond_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, cond);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_open_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_open_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, open);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_acquired_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_acquired_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, acquired);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_memory_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_memory_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, memory);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_size_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, size);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_timestamps_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_timestamps_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, timestamps);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_spec_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_spec_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, spec);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_samples_per_seg_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_samples_per_seg_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, samples_per_seg);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_empty_seg_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_empty_seg_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, empty_seg);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_state_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_state_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, state);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_segdone_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_segdone_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, segdone);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_segbase_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_segbase_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, segbase);
}

MYAPI guint gst__audiosharp_gst__audio_audioringbuffer_get_waiting_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audioringbuffer_get_waiting_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioRingBuffer, waiting);
}

MYAPI guint gst__audiosharp_gst__audio_audiosink_get_element_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiosink_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioSink, element);
}

MYAPI guint gst__audiosharp_gst__audio_audiosrc_get_element_offset (void);

MYAPI guint
gst__audiosharp_gst__audio_audiosrc_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstAudioSrc, element);
}

MYAPI guint gst__basesharp_gst__base_baseparse_get_element_offset (void);

MYAPI guint
gst__basesharp_gst__base_baseparse_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseParse, element);
}

MYAPI guint gst__basesharp_gst__base_baseparse_get_sinkpad_offset (void);

MYAPI guint
gst__basesharp_gst__base_baseparse_get_sinkpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseParse, sinkpad);
}

MYAPI guint gst__basesharp_gst__base_baseparse_get_srcpad_offset (void);

MYAPI guint
gst__basesharp_gst__base_baseparse_get_srcpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseParse, srcpad);
}

MYAPI guint gst__basesharp_gst__base_baseparse_get_flags_offset (void);

MYAPI guint
gst__basesharp_gst__base_baseparse_get_flags_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseParse, flags);
}

MYAPI guint gst__basesharp_gst__base_baseparse_get_segment_offset (void);

MYAPI guint
gst__basesharp_gst__base_baseparse_get_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseParse, segment);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_element_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, element);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_sinkpad_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_sinkpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, sinkpad);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_pad_mode_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_pad_mode_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, pad_mode);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_offset_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_offset_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, offset);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_can_activate_pull_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_can_activate_pull_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, can_activate_pull);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_can_activate_push_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_can_activate_push_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, can_activate_push);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_preroll_lock_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_preroll_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, preroll_lock);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_preroll_cond_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_preroll_cond_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, preroll_cond);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_eos_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_eos_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, eos);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_need_preroll_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_need_preroll_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, need_preroll);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_have_preroll_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_have_preroll_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, have_preroll);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_playing_async_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_playing_async_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, playing_async);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_have_newsegment_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_have_newsegment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, have_newsegment);
}

MYAPI guint gst__basesharp_gst__base_basesink_get_segment_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesink_get_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSink, segment);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_element_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, element);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_srcpad_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_srcpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, srcpad);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_live_lock_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_live_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, live_lock);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_live_cond_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_live_cond_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, live_cond);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_is_live_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_is_live_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, is_live);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_live_running_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_live_running_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, live_running);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_blocksize_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_blocksize_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, blocksize);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_can_activate_push_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_can_activate_push_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, can_activate_push);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_random_access_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_random_access_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, random_access);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_clock_id_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_clock_id_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, clock_id);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_segment_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, segment);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_need_newsegment_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_need_newsegment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, need_newsegment);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_num_buffers_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_num_buffers_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, num_buffers);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_num_buffers_left_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_num_buffers_left_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, num_buffers_left);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_typefind_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_typefind_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, typefind);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_running_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_running_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, running);
}

MYAPI guint gst__basesharp_gst__base_basesrc_get_pending_seek_offset (void);

MYAPI guint
gst__basesharp_gst__base_basesrc_get_pending_seek_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseSrc, pending_seek);
}

MYAPI guint gst__basesharp_gst__base_basetransform_get_element_offset (void);

MYAPI guint
gst__basesharp_gst__base_basetransform_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseTransform, element);
}

MYAPI guint gst__basesharp_gst__base_basetransform_get_sinkpad_offset (void);

MYAPI guint
gst__basesharp_gst__base_basetransform_get_sinkpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseTransform, sinkpad);
}

MYAPI guint gst__basesharp_gst__base_basetransform_get_srcpad_offset (void);

MYAPI guint
gst__basesharp_gst__base_basetransform_get_srcpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseTransform, srcpad);
}

MYAPI guint gst__basesharp_gst__base_basetransform_get_have_segment_offset (void);

MYAPI guint
gst__basesharp_gst__base_basetransform_get_have_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseTransform, have_segment);
}

MYAPI guint gst__basesharp_gst__base_basetransform_get_segment_offset (void);

MYAPI guint
gst__basesharp_gst__base_basetransform_get_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstBaseTransform, segment);
}

MYAPI guint gst__basesharp_gst__base_collectpads_get_data_offset (void);

MYAPI guint
gst__basesharp_gst__base_collectpads_get_data_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstCollectPads, data);
}

MYAPI guint gst__basesharp_gst__base_dataqueue_get_object_offset (void);

MYAPI guint
gst__basesharp_gst__base_dataqueue_get_object_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstDataQueue, object);
}

MYAPI guint gst__basesharp_gst__base_bytereader_get_size_offset (void);

MYAPI guint
gst__basesharp_gst__base_bytereader_get_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstByteReader, size);
}

MYAPI guint gst__basesharp_gst__base_bytereader_get_byte_offset (void);

MYAPI guint
gst__basesharp_gst__base_bytereader_get_byte_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstByteReader, byte);
}

MYAPI guint gst__controllersharp_gst__controller_timedvaluecontrolsource_get_lock_offset (void);

MYAPI guint
gst__controllersharp_gst__controller_timedvaluecontrolsource_get_lock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTimedValueControlSource, lock);
}

MYAPI guint gst__controllersharp_gst__controller_timedvaluecontrolsource_get_nvalues_offset (void);

MYAPI guint
gst__controllersharp_gst__controller_timedvaluecontrolsource_get_nvalues_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTimedValueControlSource, nvalues);
}

MYAPI guint gst__controllersharp_gst__controller_timedvaluecontrolsource_get_valid_cache_offset (void);

MYAPI guint
gst__controllersharp_gst__controller_timedvaluecontrolsource_get_valid_cache_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTimedValueControlSource, valid_cache);
}

MYAPI guint gstmpegtssharp_gstmpegts_section_get_section_type_offset (void);

//guint
//gstmpegtssharp_gstmpegts_section_get_section_type_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, section_type);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_pid_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_pid_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, pid);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_table_id_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_table_id_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, table_id);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_subtable_extension_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_subtable_extension_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, subtable_extension);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_version_number_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_version_number_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, version_number);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_current_next_indicator_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_current_next_indicator_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, current_next_indicator);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_section_number_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_section_number_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, section_number);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_last_section_number_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_last_section_number_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, last_section_number);
//}
//
//guint gstmpegtssharp_gstmpegts_section_get_crc_offset (void);
//
//guint
//gstmpegtssharp_gstmpegts_section_get_crc_offset (void)
//{
//	return (guint)G_STRUCT_OFFSET (GstMpegtsSection, crc);
//}

MYAPI guint gst__netsharp_gst__net_netclientclock_get_clock_offset (void);

MYAPI guint
gst__netsharp_gst__net_netclientclock_get_clock_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstNetClientClock, clock);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_payload_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_payload_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseAudioPayload, payload);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_base_ts_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_base_ts_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseAudioPayload, base_ts);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_frame_size_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_frame_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseAudioPayload, frame_size);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_frame_duration_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_frame_duration_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseAudioPayload, frame_duration);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_sample_size_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbaseaudiopayload_get_sample_size_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseAudioPayload, sample_size);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbasedepayload_get_sinkpad_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbasedepayload_get_sinkpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseDepayload, sinkpad);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbasedepayload_get_srcpad_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbasedepayload_get_srcpad_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseDepayload, srcpad);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbasedepayload_get_clock_rate_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbasedepayload_get_clock_rate_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseDepayload, clock_rate);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbasedepayload_get_segment_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbasedepayload_get_segment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseDepayload, segment);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbasedepayload_get_need_newsegment_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbasedepayload_get_need_newsegment_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBaseDepayload, need_newsegment);
}

MYAPI guint gst__rtpsharp_gst__rtp_rtpbasepayload_get_element_offset (void);

MYAPI guint
gst__rtpsharp_gst__rtp_rtpbasepayload_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTPBasePayload, element);
}

MYAPI guint gst__rtspsharp_gst__rtsp_rtspmessage_get_type_offset (void);

MYAPI guint
gst__rtspsharp_gst__rtsp_rtspmessage_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstRTSPMessage, type);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeymessage_get_version_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeymessage_get_version_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYMessage, version);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeymessage_get_type_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeymessage_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYMessage, type);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeymessage_get_V_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeymessage_get_V_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYMessage, V);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeymessage_get_prf_func_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeymessage_get_prf_func_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYMessage, prf_func);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeymessage_get_CSB_id_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeymessage_get_CSB_id_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYMessage, CSB_id);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeymessage_get_map_type_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeymessage_get_map_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYMessage, map_type);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeypayload_get_type_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeypayload_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYPayload, type);
}

MYAPI guint gst__sdpsharp_gst__sdp_mikeypayload_get_len_offset (void);

MYAPI guint
gst__sdpsharp_gst__sdp_mikeypayload_get_len_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstMIKEYPayload, len);
}

MYAPI guint gst__tagssharp_gst__tags_tagdemux_get_element_offset (void);

MYAPI guint
gst__tagssharp_gst__tags_tagdemux_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTagDemux, element);
}

MYAPI guint gst__tagssharp_gst__tags_tagmux_get_element_offset (void);

MYAPI guint
gst__tagssharp_gst__tags_tagmux_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstTagMux, element);
}

MYAPI guint gst__videosharp_gst__video_colorbalancechannel_get_label_offset (void);

MYAPI guint
gst__videosharp_gst__video_colorbalancechannel_get_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstColorBalanceChannel, label);
}

MYAPI guint gst__videosharp_gst__video_colorbalancechannel_get_min_value_offset (void);

MYAPI guint
gst__videosharp_gst__video_colorbalancechannel_get_min_value_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstColorBalanceChannel, min_value);
}

MYAPI guint gst__videosharp_gst__video_colorbalancechannel_get_max_value_offset (void);

MYAPI guint
gst__videosharp_gst__video_colorbalancechannel_get_max_value_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstColorBalanceChannel, max_value);
}

MYAPI guint gst__videosharp_gst__video_videobufferpool_get_bufferpool_offset (void);

MYAPI guint
gst__videosharp_gst__video_videobufferpool_get_bufferpool_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoBufferPool, bufferpool);
}

MYAPI guint gst__videosharp_gst__video_videofilter_get_element_offset (void);

MYAPI guint
gst__videosharp_gst__video_videofilter_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoFilter, element);
}

MYAPI guint gst__videosharp_gst__video_videofilter_get_negotiated_offset (void);

MYAPI guint
gst__videosharp_gst__video_videofilter_get_negotiated_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoFilter, negotiated);
}

MYAPI guint gst__videosharp_gst__video_videofilter_get_in_info_offset (void);

MYAPI guint
gst__videosharp_gst__video_videofilter_get_in_info_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoFilter, in_info);
}

MYAPI guint gst__videosharp_gst__video_videofilter_get_out_info_offset (void);

MYAPI guint
gst__videosharp_gst__video_videofilter_get_out_info_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoFilter, out_info);
}

MYAPI guint gst__videosharp_gst__video_videosink_get_element_offset (void);

MYAPI guint
gst__videosharp_gst__video_videosink_get_element_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoSink, element);
}

MYAPI guint gst__videosharp_gst__video_videosink_get_width_offset (void);

MYAPI guint
gst__videosharp_gst__video_videosink_get_width_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoSink, width);
}

MYAPI guint gst__videosharp_gst__video_videosink_get_height_offset (void);

MYAPI guint
gst__videosharp_gst__video_videosink_get_height_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GstVideoSink, height);
}

